name: Lint PR
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:      
  label:
    runs-on: ubuntu-latest
    name: Lint PR
    permissions: write-all
    steps:
      - name: label
        uses: action-runner/conventional-labeler@v1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the output
        run: echo "The labels were ${{ steps.label.outputs.labels }}"
